Repository hackclub/sinerider, pull requests merged in 2023-05, with the labels that each got.

#457 Add to loading screen
  App/main.js
  App/style.css
  Assets/Images/loading-screen.png
  Assets/Images/reddit.png
  Assets/Images/twitter.png
  Types/Entities/World.js
  index.html
Labels: enhancement, ui

#415 Display warning on mobile browsers
  App/main.js
  App/style.css
  index.html
Labels: enhancement

#371 Start rewriting README for release
  README.md
Labels: documentation, help wanted, marketing, feedback
