Repository hackclub/sinerider, pull requests merged in 2023-03, with the labels that each got.

#294 Differentiate cutscene levels from normal levels on map with rhombus shape
  Types/Entities/LevelBubble.js
Labels: enhancement

#299 Change reset button color to red
  App/style.css
Labels: enhancement, ui

#300 Add red border to expression envelope for invalid formulas
  App/style.css
  Types/Entities/Level.js
Labels: enhancement

#308 Fix dialogue going off screen in final cutscene.
  App/Levels/credits.js
Labels: bug, cutscene
