Repository hackclub/sinerider, pull requests merged in 2023-04, with the labels that each got.

#346 Proper victory screen v2
  App/main.js
  App/style.css
  Types/Entities/World.js
  index.html
Labels: user experience, ui, feedback

#351 Implement new volcano vector field
  Types/Entities/World.js
Labels: enhancement, art design

#359 Fix issue with plurality in victory screen
  Types/Entities/World.js
  index.html
Labels: bug

#360 Add hover text to both counts
  App/style.css
  index.html
Labels: enhancement, user experience, ui

#368 Happy easter dino :)
  App/dinoegg.js
  index.html
Labels: enhancement

#406 Add confirmation modal for reset equation
  App/main.js
  App/style.css
  Types/Entities/World.js
  index.html
Labels: enhancement

#404 Mention arrow keys in the constant lake cutscene message
  App/Levels/constantLake.js
Labels: enhancement
